version: '3.3'
services:
  server:
    command: ["npm","run","dev"]
    build:
      dockerfile: Dockerfile
    volumes:
      - /usr/app/node_modules
      - ./logs/:/usr/app/logs
      - ./src:/usr/app/src
    environment:
      - PORT=8080
      - SOCKET_PORT=8081
    ports:
      - "8080:8080"
      - "8081:8081"
  redis-service-cache:
    restart: always
    build:
      dockerfile: redis.Dockerfile
    ports:
      - "13333:13333"
    volumes:
      - /redis/service-cache:/data
  redis-app-cache:
      restart: always
      build:
        dockerfile: redis.Dockerfile
      ports:
        - "13334:13333"
      volumes:
        - /redis/app-cache:/data


